== プロット

(ブロローグ)

パスベルスは聖暦1922年8月、クルティアを離れ、
正統ルニアをおとずれた。9月3日、パスベルスは
西アンダルフトでアルカーンの大虐殺に遭遇する。
殺される - もうダメかと思ったとき、アルカーンは
パスベルスを見て驚く。パスベルスはパストロルスの
娘だったのだ。アルカーンはパスベルスとその仲間を
殺すことはなかった。アルカーンは別れ際にかれらに
話す。「じつはきみのお母さん(パストロルス)を殺し
たのはわたしだ。恨むがいい。わたしはしばらく東
アンダルフトに身を隠している。復習したければ
来い」と。「罠よ」とドーリアス。「行けば殺される
わ。わたしたちは逃げるべきよ」。
「どうしてわたしたちだけが
見逃されたのか？」という疑問を持ちつつ、
生きていることにただ安心する一行。

(1)

パスベルスたちはアンダルフトは危険だと思い、
できるだけアンダルフトから離れることにした。
まずはアンダルフト港の南にあるブラドック町
へ行く。かれらは9月3日の深夜に発ち、9月4日の
早朝にブラドック町に着いた。ブラドック町で
かれらは2日ほどすごした。9月5日は太陽の曜日だし、
9月6日は月の曜日だから休むことにしたのだ。9月
7日の早朝、かれらはさらに南下し、7日の昼過ぎに
バッドケイル町についた。そのあとかれらは
そこで1日過ごし、8日の早朝、アンダルノルドに
向けて出発した。アンダルノルドはアンダルフトと
同じくらい大きな都市であり、しばらくはそこで
過ごすことにしたのだ。1週間ほどして、14日の早朝、
かれらはアンダルノルド山を越えて東アンダルノルド
へ向かう。14日かれらはアンダルノルド山の山小屋で
眠りについた。15日もかれらは歩き続け、15日の早朝、
かれらはアリエ町についた。

(2)

東アンダルノルドに行くまで、かれらはしばしの
休息をとることにした。かれらは21日にアリエ町を
出ることにした。しばらくの間、かれらは平穏な毎日を
過ごしていた。偉大な魔女を継ぐ者と呼ばれるルーナと
その一行がアリエ町をおとずれたのは、9月19日のこと
だった。アルサメルはかれらが来るのを知って、突然
アリエ町を出ようと言い出す。しかし19日は太陽の曜日
であり、ドーリアスもパスベルスも行きたくはなかった。

ドーリアスはアルサメルに彼女に決闘を挑むべきだと
言う。それをテオバルムが聞き取り、ルーナの方から
やってくることになる。こうしてかれらはルーナと出会う
ことになる。

アルサメルとルーナは、10月2日に決闘をすることになった。
アルサメルは20日から10月1日まで、アデラに剣の手ほどきを受ける。
しかしアルサメルはどうしても勝てる気がしなかった。

けっきょくアルサメルはルーナに敗北する。

(3)

しかしその後、祝宴で驚くべき話を聞く。
アデラやルーナがアリエ町に来たのは、
アンダルノルドを超えて、アンダルフトまで行く
ためだったのだ。そして、その目的はアルカーンの
成敗だという。じつはアデラはアルカーンの姪であり、
アルカーンに怨みがあるのだという。アルサメルは
チャンスだと感じ、自分を雇ってほしいとルーナに頼む。
ルーナはアルサメルに雇うメリットをたずねる。
アルサメルは、そこでパスベルスに起こったことを
話し、アルカーンの居場所を知っていると言う。
アルカーンには多額の懸賞金が描けられている。
その居場所を教えるから、もしかれを
見つけた暁には懸賞金の5分を分けてほしいと
言う。分け前を少なくする代わりに、もし見つから
なかった場合は勘弁してほしいという。
ルーナはたしかに利のある話だと感じる。

(4)

// 6日間の話を書く
6日後の10月8日、かれらは東アンダルフトへ
着きアルカーンの捜索を始める。

ここでアルカーンが向こうからやってくる。
アデラがいないときのことだった。ルーナは
戦わなかった。アルカーンはパスベルスを
ここに呼んだ目的を告げる。

「おまえは…持っているはずだ。パストロルスの記した
先祖の書を。それを寄越せ」
パスベルスはたずねる。「なぜ？」
「フン、そんなのは関係がない」
パスベルスは正直そんなものを持っていなかったが、
ないと言えば殺されると思ったので嘘をついて
やり過ごそうと思った。「……ここにはありません」
「…ではどこにあるというのだ？」
「教えるわけにはいきません」
「なんだと -」
「わたしを殺しますか？　…お母さんの書は
永遠に見つからなくなりますよ。困りますよね？
それがないと、あなたは…」
「--」
「あれに書かれていることは知っています。
だから教えるわけにはいかない」
「……フン。キモの座った娘だ。
このわたしと駆け引きしようとはな」
「--」
「お前はあれに書かれていることを知らない。
それどころか、持ってすらないと見た。違うか」
「な--そ、そんなことっ」
「では、あれになにが書かれていると思う？」
「--っ、い、言えません。大事なことだから…」
「違うな。おまえは知らない」
「な、なんでそんなことっ」
「隠さずともよい。おまえが持っていないならば
おまえを殺す理由はない。もっとも、生かす理由もないが…」
「…」
「簡単に言おう。パストロルスは莫大な財産を
持っていた。だが死ぬ前にそれをどこかに隠し、
先祖の書にその在処を記してお前に与えようと
したのだ…。だからその先祖の書を横取りできれば
莫大な財産を横取りできるというわけだ。そして
先祖の書をお前が持っている、はずだったのだがな…」

アルカーンは去った。

ルーナはアルカーンを尾行し、
かれの宿を突き止める。

(5)

パスベルスたちはアルカーンを
追うことになった。パスベルスに目的のものがないと
わかった以上、アルカーンがここに残っている保証は
ない。

10月8日、深夜。アルカーンの宿を襲撃することになった。
卑怯にも思えるが、もっとも勝てそうな方法を
選ぶのが最善なのだ。あんまり大人数で行っても気づかれてしまう。
ルーナがアルカーンの宿に忍び込み、かれを殺す。
もし気づかれれば一目散に逃げる。アデラとアルサメルはそれを監視し、
もし失敗したようならルーナを援護する。パスベルスとドーリアスは
行かなくてもいいわけだが、パスベルスが「行かせてください」
と言ったので行く事になる。

ルーナは実際に忍び込み殺害を試みるが、そこにアルカーンの
姿はなかった。いくら探してもかれはいない。
「読まれていたのか」ルーナは焦り、戻る。

その頃、パスベルスは背後に寒気を感じる。
「アルカーンだッ」と言ったときにはすでに遅く、
パスベルスはかれに捕縛されてしまう。
ドーリアスは這いつくばって逃げる。

アデラとアルサメルは悲鳴に気づき、助けようとするが
アルカーンがパスベルスを人質にしたので動けない。

アルカーンは言う。
「ふふ、はははは！　よもやお前が現れるとは思わなかったぞ、アデラ！」
「叔父さん(アルカーン)……」
「先祖の書を持たない以上、この娘に情けをかける理由はなかったが、
いまやそれが変わり、この娘には人質としての価値が十分に
備わった。アデラ！　愛しい我が姪よ！
2日待つ。西アンダルフトの港に来い。
1人でだ！　10月10日の深夜に決闘をしようではないか。
もしおまえが勝てば娘は返そう。おまえが負けるか、あるいは
来なければ……この娘の命はない」

そこへアルカーンの背後にルーナが切り掛かる。
しかしアルカーンはひらりと身をかわす。
ルーナは怒濤の攻撃を仕掛けるが、アルカーンに退けられてしまう。

「…わたしはおまえが誰だか知らないが、アデラの
友人かね？」
「…腐れ縁だけどね」
「フフ、そうか。彼女は友に恵まれたようだ」

そのとき、ドーリアスが悲鳴にならない悲鳴をあげる。
「----ッ」
ドーリアスは崩れ落ち、アルサメルが彼女を支える。
「どうした！？　大丈夫か！？」
「耳が----ッ」
「耳？」
「すごい大きな耳鳴りが…！」

アルカーンは言う。
「ほう、その娘は聞き手か」

そのあと、アルカーンの体が閃光に包まれる。
ドーリアスは地面に足をついて耳を抑える。
「----ッ」
「やつ(アルカーン)の仕業か…！？」
アルカーンは閃光の中で答える。
「その娘に謝っておいてくれ。どうやらこの業は
音ならざる音を響かせるらしく、たまにそれをひどく
不快に感じる者もおるようなのだ。なに、害はない」

閃光が渦巻いて消えるともに、アルカーンの
姿は消えていた。

(6)

パスベルスは仰天する。
「ここ…西アンダルフトじゃないですか」

アルカーンは答える。
「そう…パストロルスを死に至らしめた忌まわしい
土地だ」

「わたし眠っていたんですかね。そんな覚えはないんですけど」

「眠っていたようには見えないが？」

「今日は10月8日ですよね？」

「時刻としてはつい数十分前に10月9日に切り替わったようだ」

「…いずれにせよ、西アンダルフトと東アンダルフトはアンダルフト山によって
区切られていて、その山を越えるのにはまる1日かかるはずです…いったいどうやって
来たんですか」

「教えるぎりはない」

「気になるんです」

「…　じつを言うとわたしにもよくわからない。
やり方を教えてもらったのだが、原理がどうなっているのかは
よくわからない。たとえばきみは、冷蔵庫で食品を
冷やす方法は知っていると思うが、それがどうして冷えるのか
説明できるかね？」

「……できません」

「わたしはある者からその方法を教わった、が、
原理はよくわからないし、やり方を教えることもできん
のだ…。とにかくわかるのは、それをすればある場所から別の
場所に転移できるということだ。わたしはこの能力の
おかげでこれまで数々の窮地を脱してきたのだ」

「…　聞きたいことがあるんです。
9月3日、どうしてわたしたちを…見逃したんですか」

「なぜそのようなことを聞く」

「あなたの目的はお母さんの財産だったはず。
ならあのときわたしを捕らえて拷問することだってできたはずじゃないですか。
でもなぜそうしなかったのでしょう。わたしにはなにか理由があるように思えて…」

「気まぐれだ。悪いか？」

「…」

「……わたしはベアン人を殺さないのだ。
義妹がベアン人であったからな」

「！！　それって……」

「死にたかったか？」

「人種差別です」

「ならこの場で殺してやろうか？」

「！　そ、それは…」

「……それに、おまえがパストロルスの娘だというのは
ひとめでわかった。金髪で碧眼のベアン人はそういない。
血筋の者であると判断するのは自然だ」

「で、でも、それがどう関係するんですか？」

「わたしは9月3日、パストロルスの弔いをしていたのだ。
あれほどの賢人を今世紀に見ることはもはや叶わないだろう。
西アンダルフトはパストロルスが没した地。
彼女に魂を送り届けてやったのだ」

「それって……人をたくさん殺すことが、
弔いだって言うんですか？」

「そうだ」

「狂ってます……」

「……」

それから 2日間、パスベルスはアルカーンと
ともに過ごしていた。パスベルスは、しばらく
かれと触れ合ってみてわかったことがひとつあった。
かれは本当に好きで人殺しをしているということ
だ。それに反論すれば殺されてしまうかもしれないので
パスベルスは反論しなかった。パスベルスは
かれを狂っていると評価した。

そして10日の深夜。アデラが1人で現れる。

「来たなアデラ…」

「叔父さん(アルカーン)…」

「まずは挨拶をしよう。26……いや、27年ぶりか？
大きくなった…いや、老けたと言うべきか」

「……わたしはその日付を1度たりとも忘れたことはありません。
あなたは覚えていないでしょうけど。今日はあれから28年と4ヶ月め
です。1894年6月7日は……お母さんの命日ですもの」

「そうか…そうだったな」

「聞きたいことがあります」

「なんだね？」

「どうしてお母さんを殺したのか」

「ははは、そんなことはどうでもいいじゃないか」

「…！」

「そんなことよりわたしはおまえを呼んだ。
彼女(パスベルス)を人質にしてだ」

「…」

「その理由の方が話したい…それは、成長したきみと
ぜひ殺し合いを楽しみたいからだ…1対1の…水入らずの戦いを」

「…　狂気」

「広いところへ行こう。こそこそと逃げ回る卑怯な暗殺者に介入されては興ざめだ…」

アデラとアルカーンが戦う。けっきょく、アデラは追いつめられてしまう。
アデラはL字の形の建物の角に追いつめられてしまう。
「くっ…」
「終わりだ」
「…」
「きみもお母さんと同じ場所へ行くのだ…」
「それはどうかな」
「ん？」
「あなたはわたしを追いつめたのではなく…わたしに誘い込まれたのよ」

そこへ突如として屋根の上からルーナとアルサメルが登場し、
飛び降りて一閃。アルカーンを斬る。

「ウウッ…」

アルカーンは利き腕を斬られて剣を落とす。
残った腕で利き腕を抑え走り出す。
しかし左足も斬られておりうまく走れない。
その背中をアデラが蹴り倒し、かれの
うつぶせに倒れ込むかれののど元に切っ先を
突きつける。

「終りね」

「…見事だ。わたしの負けだ」

「…　最後にあなたに聞きたかったけど…やめておく」

「…」

「あなたには賞金がかけられてる。それも大変な、ね。
おまけに、正統ルニアの政府は生死を問わないと言ってる。
これがどういう意味かわかる？」

「…」

「この人殺しめ。今度はあなたの番ということよ」

パスベルスはそのやり取りを見て不安を感じ、アルから短剣を
奪うと、アルカーンの胸を目がけて振り下ろそうとする。
しかし勇気が出ずにうまくできない。

「な、なにしてるの！？」

パスベルスは答える。

「この人、転移の魔法を使うんです！　どうやってかは
わかりませんけど…とにかく、殺せるときに殺しておかないと、
危ない」

「パスベルスの言うとおりだ」

そこでアルカーンの体が光りだす。

「転移だ！」と、パスベルス。

と、同時にドーリアスが耳を塞いで倒れる。

「きゃああああ！　うるさい！　うるさいうるさいうるさい」

「またあのときの--」

ドーリアスが「黙って！」と叫ぶ。
するとアルカーンの体の発光が止まる。
仰天するアルカーン。「一体…」

「止まった…」と、ドーリアス。

アルカーン「どうやら命運尽きたようだ」

ルーナ「ど、どういうこと？」

パスベルス「わかりませんが…とにかくかれは転移に失敗したようです」

ルーナ「それで…アデラ、どうするの？　かれを殺すの？　復讐を、
果たしたいんでしょう？」

アデラ「…それではかれと同じになってしまう。
かれを逮捕して、正統ルニアの警察に引き渡す。
かれは何人もの人を殺しているわ。わたしが手を
下さずとも、あとは、法の裁きを受けるまででしょう」

ルーナ「あなたはキレイなやり方が好きなのよね」

アデラ「これでも元警察なのよ」

(終幕)

こうしてアルカーンは逮捕された。
そのあと、ルーナはアルカーンを政府に引き渡し、
莫大な賞金を手に入れた。アルサメルの一行は
分け前を手に入れ、数ヶ月は遊んで暮らした。

しかしパスベルスは気になることがひとつあった。
あのときドーリアスに起こったこと。アルカーンが転移の
魔法を使うと、ドーリアスが苦しむこと。アルカーンの転移の
魔法が、どういうわけか中断されたこと。

パスベルスの立てた仮説はこうだ。あのとき、ドーリアスは「黙って！」
と叫んだ。それがなんらかのトリガーになったのではないだろうか。
つまり、ドーリアスが嫌だと感じたから、アルカーンの
転移の魔法は中断されたのだ。

手がかりはひとつ。アルカーンの言葉である「聞き手」という
単語だ。聞き手……それは、いくつかの文献で見られた。
多くは神話やオカルトの類いであった。よれば、
世の中には大きく分けて「話し手」と「聞き手」という
存在がある。「話し手」というのは、魔法を使える
人のこと。しかし魔法というのは元来人間には関知できない
能力なのだ。「聞き手」というのは、魔法を関知できる人の
こと。「聞き手」にとって、魔法というのは大きな不協和音のように
感じられ、とても不快な轟音を成すのだという。

しかし、「聞き手」は音を聞くことはできるが、
魔法に影響を及ぼすことはできない。
では、「話し手」はどうだろうか。「話し手」は、
他人の魔法に干渉して中断させたりできるのだという。

ドーリアスは、「話し手」なのだろうか……？
しかし、パスベルスはそれくらいを調べたあと、
やめた。あまりにもバカらしいと思ったのだ。
仮説なんてもっともらしい言葉を使っているが、
けっきょく、つじつま合わせに過ぎないのだ。


