= 砂漠の巨人 上 読了

http://minadukinaduki.web.fc2.com/sara1.htm>[砂漠の巨人 上] 読了。
面白かった。ルカ強過ぎやねん。
リツコさん×エリィちゃんが公式らしい。
軍隊がほとんど女性で構成されているので、
たぶんこの世界では女性のほうが男性より優遇されているのだろう

最初、やたらみんな炎を使うなぁって思った。
エリィは炎の剣、ルカは火球、さらにビリーも途中で炎の使い手であることが
明らかになる。リツコは地味すぎる気がした。

あとルカが12人も同時に倒してたりしてヤバい。
さらにルカは治療もできる。それも魔術ではなくビリーに手術っぽいことをしていて
チート的な性能である。

エリィはなぜ敵の兵士を見逃したのだろう？
動けないから殺す必要はないと思ったのかな？
それとも実は心優しくて人殺しは好きじゃないみたいな？
でも後々の戦局のことを考えるとあそこは殺害しておくべきだったのでは…

女性多すぎやろw
敵も味方も女性ばかり。
気持ちはとてもよくわかる


設定を参考にしたいので、個人的にまとめる。
まだ読んでない人はネタバレに注意してください

== 舞台について

舞台は地球ではないけど、地球とリンクしているらしく、地球は西暦2024年頃
らしい。 footnote:[「グレゴリウス暦二〇十二年――今から十二年前、当時私がまだ七歳だった頃――私たちの世界に一つ目の塔が現れた」] 。地球はこの世界では **イヴの世界** と呼ばれている
footnote:[私のいた世界は私の国ではイヴの世界って呼ばれてた] 。

*世界について* この世界ではいくつかの世界が登場する。
各世界には異世界と繋がる塔が2つ存在するといわれている
footnote:[塔は不可能を可能にしてくれる夢のような存在だ。塔を介して別の世界へと渡り、元の世界には存在しないような知識、技術、あるいは鉱石などの希少な物質を持ち帰ることができる。それは現在、一つの世界に二つずつしか存在しないといわれている異世界への架け橋だ] 。

* イヴの世界 - 地球のこと
* サラの世界 - 砂漠の巨人の主な舞台。マディミール大陸がある。マッドベース、マッドスコープ、マッドガルドなどがある
* リーヴの世界 - アステナ王国などがある
* アイリスの世界 - ロモコ大陸がある。エルザリア連合王国などがある

*イヴの世界について*
塔はスペインと日本にある。

*サラの世界について*
塔はマッドスコープとマッドベースにある。

* マディミール大陸 - サラの世界にある大陸。ほとんどが砂漠らしい
* マッドスコープ - マディミール大陸の北西にある国
footnote:[マディミール大陸は丁度ヘアピンのような形をしている。泥砂海と呼ばれる海を挟んで南東にあるのがマッドガルド、その北西に位置するのがマッドスコープだ。そのマッドスコープの領土の東端には、マッドガルド側の海に面したところで大きく弧状に突き出た半島がある。マッドスコープの本土を防衛するに当たって重要な拠点となるスラージャ半島だ。] 。
* マッドベース - マッドスコープとマッドガルドの間にあるらしい。
* マッドガルド - マディミール大陸の南東にある国
footnote:[マディミール大陸は丁度ヘアピンのような形をしている。泥砂海と呼ばれる海を挟んで南東にあるのがマッドガルド、その北西に位置するのがマッドスコープだ。そのマッドスコープの領土の東端には、マッドガルド側の海に面したところで大きく弧状に突き出た半島がある。マッドスコープの本土を防衛するに当たって重要な拠点となるスラージャ半島だ。] 。
* サゴマ - マッドベースに住んでいるエイリアンのような種族。
  地球とよく似た文明を持つ。子供のような背丈を持ち、頭部は
  大きく豆の形をしている。頭部の側面には握りこぶしほどの複眼を持つ。
  また、たぶん人の目と同じくらいの位置にカエルの卵のように小さな単眼を持つ。
  鼻孔はあるが、鼻はない。音は聞こえるらしいが、人間の耳のように頭部の
  側面にでっぱっている外耳は持たない。毛髪もない。
  腹は透き通っており、内蔵が見えている。
  人間の声帯を持たないため、生まれたままでは
  人の言葉を話すことはできない。人工声帯を使えば話すことができる。
  食事は2,3日に1度しかとらない。体温が50度や30度になっても死ぬことはない。
  睡眠時間は長い。寿命は長い。出産は遅い。
  食べ物は人間と同じようなものを食べるらしい。
* 火力船 - 炎を動力として飛ぶ船。ザラの能力を使って動かす。
* マディミール語 - マディミール大陸で使われている言葉らしい
* サゴマの言葉 - 乾燥した蓮の実のような器官から発せられる特殊な音波によって
  発音される言葉。人間に聞き取ることはできないし、もちろん話すこともできない。
* ガルナディア - マッドガルドの首都

*リーヴの世界*
塔はアステナ王国にある。

* アステナ王国 - 高度な魔術文明を有する国
* アストラピア - アステナ政府によって設立された塔の研究をする機関。
  軍隊も持っているらしい。
* テレーニュ - アステナで使われている言葉らしい。テレネア語から派生した。

*アイリスの世界*

* エルザリア連合王国 - ロモコ大陸にある国
* ミルザ - ロモコ大陸にある国らしい
* ヴェロニカ - ロモコ大陸にある国らしい
* ロディーナ - エルザリア、ミルザ、ヴェロニカなどで使われている文字。
* アリアーネ - ロモコ大陸の古都

*分類不明*

* テレネア語 - 統一言語で、アステナ以外でも使われている。
* クレオール語 - どこかで使われている言葉らしいが、どこで使われているかに関する描写はない
* リング - 魔術師が持ち物を運ぶ時に使うもの。形状はペンダントなど輪ではないものもあるっぽいが、
  最初は指輪の形でつくられたものが多かったためリングと呼ばれている。
* 硬化ウィルス - 人工的に組み替えられた塩基配列を持つDNAのウィルス。人体に投与し、コントロールすることで
  皮膚をダイヤモンドのように固くできる。

== 登場人物

* リツコ - たぶん全体を通しての主人公。たぶん2005年生まれ
footnote:[「グレゴリウス暦二〇十二年――今から十二年前、当時私がまだ七歳だった頃――私たちの世界に一つ目の塔が現れた」]
。19歳。女性。日本人。エストラピア3番隊の1員。
* エリィ - 炎を操る剣士。体は女だけど精神は男らしい。ザラ。エストラピア3番隊の1員。
* ルカ - アステナ王国国家認定の中級魔術師
footnote:[「魔術師。アステナ王国国家認定の中級魔術師。どこの馬の骨とも分からない野良魔法使いって訳じゃないから安心しなさい」]
。女性。人間(?)。エストラピア3番隊の1員。
* ビリー - ザラとロモコ民族の末裔
footnote:[「ザラはかつてサゴマと一緒にマッドベースで暮らしていたらしい。それがやがてマッドベースの塔からアイリスの世界に現れ、ロモコ大陸へ移住してきた。当時その塔の近辺に住んでいたロモコ民族と、移住してきたザラとの混血の子孫が俺ってわけだ。(…略…)」]
。 男性。
* フレイ - ビリーの隊の隊長。少佐。マッドガルド軍に拘束されているらしい。
* ジャック・スリーロード - エストラピア3番隊の隊長。曹長。
* ラヴェンナ・ベルクシュタイン - エルザリア連合王国の使者。女性。高い能力を持つ魔術師らしい。
* ルピカ・ロロ＝マッドスコープ - マッドスコーブの王子
* リンフォーネ・ローデヴェイク - マッドガルドの近衛隊長。中尉。序盤でビリーを刺した女。
* ファーナ - マッドガルドの最高指導者。女王。
* シルカ・メルヴィル - マッドガルドの高度な魔術師。大佐。女性。
* メリー - マッドガルドの参謀長官。女性。本を読むのが好きらしい
* リアン・フラヴィニー - アステナ出身の上級魔術師。大尉。女性。
* グリフィス - 魔術師らしい。男性。
* サルヴァレッツァ - 魔術師の1人。

== 中 読了

http://minadukinaduki.web.fc2.com/sara4.htm[砂漠の巨人　中]

中ではメリーの強さが明らかにされる。
またエリィの過去について触れられる。

== 下 読了

http://minadukinaduki.web.fc2.com/sara6.htm[砂漠の巨人　下]

下ではリツコの能力について触れられる。
いままでなんの能力も持たない人かと思っていたけど……。
この時点は「2024年の地球にそんな人がいるわけねーだろ！」
と感じていた。ソルケット会戦が始まる。
リツコの舞台は敵の攻撃によって全滅したかに思われたが、
運良くリツコはサゴマに救助されたため無事だった。

== 終 読了

http://minadukinaduki.web.fc2.com/sara9.htm[砂漠の巨人　終]

終はとくに面白かった。

はじめのほうのある会話がなるほどなぁと思った。
魔法を使う文明で育っていない人が魔法を使えない
理由は、生まれつき使えないということではなく、
たとえば自転車の乗り方がわからない子供が
自転車に乗れないように、魔法の概念を直感で
理解できていないからだというのだ。
ほとんどのファンタジーでは、普通、魔法は
生まれ持った魔力を糧にして使うものとされている。
砂漠の巨人では、そうではなく、使い方がわかれば誰でも使えると
いうのだ。

ただそうなると、魔法文明に育つ人は、ほとんどが
魔術師になりそうだ。もちろん高度な魔法は使えないのだろうけど、
簡単な魔術(火をつけるとか？)なら誰でも使えそうな気がする。

以下引用。

____
「自転車に乗ったことはあるか？」 +
　ジャックは帽子を脱いで脇に置くとすぐに話を切り出した。 +
「自転車ですか？」 +
　リツコはそのまま聞き返した。 +
「あぁ。原動機を用いずに人の足でこいで前に進む二輪車だ」 +
「ええ、あります」 +
　何のことだろうとリツコは思った。 +
「そうか」 +
　いつもそうするようにジャックは足を大きく開いて膝の上に肘を乗せ、前傾の姿勢になって話を続けた。 +
「俺はかつて、歳の離れた弟がまだ幼かった頃に自転車の乗り方を教えてやったことがある」 +
　ルカはジャックの横で背筋を伸ばして椅子に座り、ぴったり揃えた膝の上に両手を乗せて黙って話を聞いている。 +
「あるとき、弟が自転車を停止させた状態のまま均衡を保とうとしていたことがあった。ハンドルを握って、両足でペダルを踏んだままでな。そんとき俺は『何やってんだ』って何の気なしに聞いてみたら、弟はこう答えたんだ。『動いてる自転車に乗るためには、まずは止まってる自転車に乗れなきゃだめだ』って」 +
「何それ」 +
　リツコはくすりと笑った。 +
「おかしいと思うだろ。でもその発言は俺に一つの示唆を与えてくれた」 +
　まぁ待てよ、とでも言うようにジャックは右手を小さく縦に振る。 +
「俺にとっては簡単な話だったんだ。車輪は転がせば前に進む。進む速度が速ければ速いほどその軌道は安定する。逆に速度が落ちれば車輪はふらつき、果てには倒れる。ただの車輪ならいざ知らず、人の乗った自転車が静止した状態でその均衡を保つだなんて無茶な話だ。当たり前のことだよな。俺にとってはそうだった。でもまだ小さい子供だった頃の弟にとってはそれが逆で、人が動いている自転車に乗っていることのほうが不思議だったんだ。止まってる自転車に乗ることのほうが簡単だと思ってたんだ」 +
「なるほど」 +
「だから乗れなかった。こげば倒れずに前に進むってことを知らなかったから。そこで俺は教えてやった。止まってるものの上に乗るほうが簡単そうに思えるが、自転車はそうじゃないんだって。小銭を転がしてみせてやった。ほら、速く転がしたほうがまっすぐ前に進むだろう？　ってな。するとどうだ。今度は上手に乗れるじゃないか。そのことを聞かせてやってからは弟は順調に上達してすぐに乗れるようになったんだ」 +
「つまり、車輪は速く転がせば倒れずに前に進むということを知らないから、私は自転車に乗れないと？」 +
「俺が言いたいのは、誤った観念は学習を著しく阻害するってことだ――ルカ、続きを頼む」 +
　ジャックはそう言って今度はルカに話を促す。ルカは小さく咳払いをしてリツコのほうへ向き直った。 +
「あのね、実はあなたみたいに魔法文明圏の外で生まれ育った人が魔術の習得に苦労するっていうのは珍しいことじゃないのよ。なぜだと思う？」 +
「やっぱり、生まれつきの素質とか……血筋？」 +
「ううん、違う」 +
　ルカは静かに首を振る。 +
「才能の差はあれど、魔術は訓練さえすれば誰しも扱うことができるようになる。魔術の習得にはいくつかの原則があるんだけど、これはその中でも特に頑健なものの一つなの」 +
「じゃあ、どうして？」 +
　リツコは続きを促した。 +
「もう一つの原則。魔術の習得には、幼少期の生まれ育った環境、文化的背景が強く影響する」 +
　ルカは教科書の一文をそらんじるようにして言ってみせた。 +
「生まれつきの素質とか、血筋とか、そういう先天的な要因は魔術の才能の多寡には影響するけれど、魔術が使えるかどうかには関係ないの。新たに魔術を習い始める人間に強く影響するのは、むしろ後天的な要因。いかに魔術が自分たちの生活と密接に関わる環境で過ごしてきたかということなのよ。日常的に魔術がありふれたものとして存在している中で生活してきた者ほど魔術の習得は容易になり、逆にそういった体験のない者は困難になる。ここまではいい？」 +
「うん」 +
　リツコはこくりとうなづいた。 +
「人間の頭の中には日常生活での経験から自然と生じる思い込みによって構築されていく概念があってね、難しい専門用語は色々とあるんだけど、ここではまぁ仮に直感的知識としておきましょう」 +
「直感的知識？」 +
「今ここで仮にそう呼ぶだけよ。ものは落とせば下に落ちるとか、玉を転がしてもいずれ止まるとか、そういう知識って学校で習わなくても実体験の中から自然と身につけていくでしょう？　そういったものって、学習場面において理解を促進することもあるけれど、逆に理解を阻害することもあるのよ。新しい知識と自身が既に備えているイメージとの食い違いからね。まぁ、こう言ってもいまいちピンと来ないでしょうから、具体的に言うと――」 +
　何があったかな、と頭の中の記憶を探るようにルカは上に目を向けて左手の指で右の手のひらを何度か叩く。 +
「例えば天動説」 +
　上方にそらしていた視線を正面に戻してルカは言う。 +
「私たちが地上にいる限り、私たちの踏んでいる地面は全くの平板なものであるようにしか思えない。それが日常生活の中から得られる直感的知識。だからかつての人々はこの星が実は丸いだなんてことはなかなか信じることができなかった」 +
　ルカは身振り手振りを交えて話を続ける。ジャックは体を起こして腕を組み、黙ってルカの話を聞きながら同調するようにたびたびうなづく。 +
「例えば光の速度。直感的には、光は光源から地の果てまで瞬時に達するように思われる。だけど実際には光は一定の速度で進むとされる。私たちはそれを知識として飲み込むことはできても、感覚的に体験することは難しい」 +
「なるほど」 +
「ここで一つクイズを出しましょう」 +
　何かをささげ持つようにルカは左手を上に向けた。すると、ぽんっと小気味よい音を立てて小さな鞄が現れる。 +
　ルカは鞄の中から手帳とペンを取り出すと、ページを開いて何かを描き始める。 +
「ある列車の車両の中で、床に紐をくくりつけられた風船が一つ浮かんでいるとします」 +
　ルカは開いたページをリツコに見せ、ペンで絵を指し示す。そこに描かれているのは横長の四角が一つと、その一辺から線分で結ばれた円が内部に一つ。四角の外には「車両」、円の横には「風船」と書かれていた。全体的に文字が細長く、丸みととがりの共存する筆跡だ。 +
「ここで列車が左へ加速すると、風船の動きはどうなるでしょう？」 +
「……右に傾く？」 +
「いいえ。答えは左よ」 +
「えっ、なんで！？」 +
　リツコは驚いた。 +
「安心して。私も最初は騙されたから」 +
　そう言ってルカは安心させるように笑みを浮かべる。 +
「俺もだ」 +
　腕を組んだままの姿勢でジャックがにやりと笑う。 +
「一体どういうことなの？」 +
　リツコはルカに解説をせかす。 +
「あのね、そもそも風船はなぜ宙に浮いていると思う？」 +
「そりゃあ、中のガスの比重が空気よりも軽いから」 +
「それじゃ、列車が加速すると風船はどうなる？」 +
「風船の紐が列車の床に引っ張られて、後ろへ傾く……ってことなんじゃないの？」 +
「違う違う。それが直感的知識の錯誤なのよ」 +
「でもつり革は後ろに傾くじゃん。あれも慣性の法則でしょ？」 +
「これはつり革じゃなくて風船なの。慣性の法則の影響を受けるのは風船だけじゃなくて車両内の空気も一緒。そして風船の中身は空気よりも軽いでしょ？」 +
「――あぁ！」 +
　リツコは指を鳴らした。 +
「騙された！！」 +
　列車が加速すると、車両内の空気は慣性の法則によってその場にとどまろうとするため、列車の前部と後部で気圧差が生じる。さながら重力の影響を受けているときに風船が空気よりも上に浮かぶように、列車が加速すると比重の軽い風船は車両の後部へ集まった空気によって押し出されて前へ傾くというわけだったのだ。 +
「だって普通列車の床に風船くくりつけるだなんて光景見ることないから、そんなの分かるわけがないよ」 +
「そこが鍵なのよ」 +
　リツコが不満を漏らすと、核心を突くようにルカが言う。 +
「実際に体感したことがないから理解できない。それがあなたにとっての魔術なの。だからリツコが魔術を使うっていうのは、列車の床に風船をくくりつけるようなものなのよ」 +
____

あと、マディミール大陸では、むかしは
識字率が高くなかったから、時計の時刻を文字盤ではなく
12色の色にして識別するようだ。

____
「それはマディミール大陸の国々に受け継がれる伝統的な様式の時計です」 +
「やっぱり、これは色で時間を表してるの？」 +
「ええ、そうです。十二色の色がそれぞれ十二個の数字に対応しています。赤は一、橙色は二、黄色は三、黄緑は四、緑は五、青緑は六、水色は七、青は八、藍色は九、紫は十、桃色は十一、赤紫は十二を指します。今は左の窓に水色、右の窓に桃色が出ているので、時刻はおおよそ七時五十五分ということになりますね」 +
____

