= 砂漠の巨人 上 読了

http://minadukinaduki.web.fc2.com/sara1.htm>[砂漠の巨人 上] 読了。
面白かった。ルカ強過ぎやねん。
リツコさん×エリィちゃんが公式らしい。
軍隊がほとんど女性で構成されているので、
たぶんこの世界では女性のほうが男性より優遇されているのだろう

最初、やたらみんな炎を使うなぁって思った。
エリィは炎の剣、ルカは火球、さらにビリーも途中で炎の使い手であることが
明らかになる。リツコは地味すぎる気がした。

あとルカが12人も同時に倒してたりしてヤバい。
さらにルカは治療もできる。それも魔術ではなくビリーに手術っぽいことをしていて
チート的な性能である。

エリィはなぜ敵の兵士を見逃したのだろう？
動けないから殺す必要はないと思ったのかな？
それとも実は心優しくて人殺しは好きじゃないみたいな？
でも後々の戦局のことを考えるとあそこは殺害しておくべきだったのでは…

女性多すぎやろw
敵も味方も女性ばかり。
気持ちはとてもよくわかる


設定を参考にしたいので、個人的にまとめる。
まだ読んでない人はネタバレに注意してください

== 舞台について

舞台は地球ではないけど、地球とリンクしているらしく、地球は西暦2024年頃
らしい。 footnote:[「グレゴリウス暦二〇十二年――今から十二年前、当時私がまだ七歳だった頃――私たちの世界に一つ目の塔が現れた」] 。地球はこの世界では **イヴの世界** と呼ばれている
footnote:[私のいた世界は私の国ではイヴの世界って呼ばれてた] 。

*世界について* この世界ではいくつかの世界が登場する。
各世界には異世界と繋がる塔が2つ存在するといわれている
footnote:[塔は不可能を可能にしてくれる夢のような存在だ。塔を介して別の世界へと渡り、元の世界には存在しないような知識、技術、あるいは鉱石などの希少な物質を持ち帰ることができる。それは現在、一つの世界に二つずつしか存在しないといわれている異世界への架け橋だ] 。

* イヴの世界 - 地球のこと
* サラの世界 - 砂漠の巨人の主な舞台。マディミール大陸がある。マッドベース、マッドスコープ、マッドガルドなどがある
* リーヴの世界 - アステナ王国などがある
* アイリスの世界 - ロモコ大陸がある。エルザリア連合王国などがある

*イヴの世界について*
塔はスペインと日本にある。

*サラの世界について*
塔はマッドスコープとマッドベースにある。

* マディミール大陸 - サラの世界にある大陸。ほとんどが砂漠らしい
* マッドスコープ - マディミール大陸の北西にある国
footnote:[マディミール大陸は丁度ヘアピンのような形をしている。泥砂海と呼ばれる海を挟んで南東にあるのがマッドガルド、その北西に位置するのがマッドスコープだ。そのマッドスコープの領土の東端には、マッドガルド側の海に面したところで大きく弧状に突き出た半島がある。マッドスコープの本土を防衛するに当たって重要な拠点となるスラージャ半島だ。] 。
* マッドベース - マッドスコープとマッドガルドの間にあるらしい。
* マッドガルド - マディミール大陸の南東にある国
footnote:[マディミール大陸は丁度ヘアピンのような形をしている。泥砂海と呼ばれる海を挟んで南東にあるのがマッドガルド、その北西に位置するのがマッドスコープだ。そのマッドスコープの領土の東端には、マッドガルド側の海に面したところで大きく弧状に突き出た半島がある。マッドスコープの本土を防衛するに当たって重要な拠点となるスラージャ半島だ。] 。
* サゴマ - マッドベースに住んでいるエイリアンのような種族。
  地球とよく似た文明を持つ。子供のような背丈を持ち、頭部は
  大きく豆の形をしている。頭部の側面には握りこぶしほどの複眼を持つ。
  また、たぶん人の目と同じくらいの位置にカエルの卵のように小さな単眼を持つ。
  鼻孔はあるが、鼻はない。音は聞こえるらしいが、人間の耳のように頭部の
  側面にでっぱっている外耳は持たない。毛髪もない。
  腹は透き通っており、内蔵が見えている。
  人間の声帯を持たないため、生まれたままでは
  人の言葉を話すことはできない。人工声帯を使えば話すことができる。
  食事は2,3日に1度しかとらない。体温が50度や30度になっても死ぬことはない。
  睡眠時間は長い。寿命は長い。出産は遅い。
  食べ物は人間と同じようなものを食べるらしい。
* 火力船 - 炎を動力として飛ぶ船。ザラの能力を使って動かす。
* マディミール語 - マディミール大陸で使われている言葉らしい
* サゴマの言葉 - 乾燥した蓮の実のような器官から発せられる特殊な音波によって
  発音される言葉。人間に聞き取ることはできないし、もちろん話すこともできない。
* ガルナディア - マッドガルドの首都

*リーヴの世界*
塔はアステナ王国にある。

* アステナ王国 - 高度な魔術文明を有する国
* アストラピア - アステナ政府によって設立された塔の研究をする機関。
  軍隊も持っているらしい。
* テレーニュ - アステナで使われている言葉らしい。テレネア語から派生した。

*アイリスの世界*

* エルザリア連合王国 - ロモコ大陸にある国
* ミルザ - ロモコ大陸にある国らしい
* ヴェロニカ - ロモコ大陸にある国らしい
* ロディーナ - エルザリア、ミルザ、ヴェロニカなどで使われている文字。
* アリアーネ - ロモコ大陸の古都

*分類不明*

* テレネア語 - 統一言語で、アステナ以外でも使われている。
* クレオール語 - どこかで使われている言葉らしいが、どこで使われているかに関する描写はない
* リング - 魔術師が持ち物を運ぶ時に使うもの。形状はペンダントなど輪ではないものもあるっぽいが、
  最初は指輪の形でつくられたものが多かったためリングと呼ばれている。
* 硬化ウィルス - 人工的に組み替えられた塩基配列を持つDNAのウィルス。人体に投与し、コントロールすることで
  皮膚をダイヤモンドのように固くできる。

== 登場人物

* リツコ - たぶん全体を通しての主人公。たぶん2005年生まれ
footnote:[「グレゴリウス暦二〇十二年――今から十二年前、当時私がまだ七歳だった頃――私たちの世界に一つ目の塔が現れた」]
。19歳。女性。日本人。エストラピア3番隊の1員。
* エリィ - 炎を操る剣士。体は女だけど精神は男らしい。ザラ。エストラピア3番隊の1員。
* ルカ - アステナ王国国家認定の中級魔術師
footnote:[「魔術師。アステナ王国国家認定の中級魔術師。どこの馬の骨とも分からない野良魔法使いって訳じゃないから安心しなさい」]
。女性。人間(?)。エストラピア3番隊の1員。
* ビリー - ザラとロモコ民族の末裔
footnote:[「ザラはかつてサゴマと一緒にマッドベースで暮らしていたらしい。それがやがてマッドベースの塔からアイリスの世界に現れ、ロモコ大陸へ移住してきた。当時その塔の近辺に住んでいたロモコ民族と、移住してきたザラとの混血の子孫が俺ってわけだ。(…略…)」]
。 男性。
* フレイ - ビリーの隊の隊長。少佐。マッドガルド軍に拘束されているらしい。
* ジャック・スリーロード - エストラピア3番隊の隊長。曹長。
* ラヴェンナ・ベルクシュタイン - エルザリア連合王国の使者。女性。高い能力を持つ魔術師らしい。
* ルピカ・ロロ＝マッドスコープ - マッドスコーブの王子
* リンフォーネ・ローデヴェイク - マッドガルドの近衛隊長。中尉。序盤でビリーを刺した女。
* ファーナ - マッドガルドの最高指導者。女王。
* シルカ・メルヴィル - マッドガルドの高度な魔術師。大佐。女性。
* メリー - マッドガルドの参謀長官。女性。本を読むのが好きらしい
* リアン・フラヴィニー - アステナ出身の上級魔術師。大尉。女性。
* グリフィス - 魔術師らしい。男性。
* サルヴァレッツァ - 魔術師の1人。
