= ふたりのハードプロブレム読んだ

http://mayuragicenter.yu-yake.com/hpot.html[ふたりのハードプロブレム]
を読んだ。

全体として、まず話の流れが自然で読みやすく面白い。
文章の書き方や物語の構成の仕方がすごくうまいなぁと
思った。登場人物の登場のさせ方や、話の展開のさせ方が
うまい。なにがうまいって、「どうして？？？」と
感じない。小説を読んでいると、ときどき「このキャラは
どうしてこういう行動をしたんだろう？」と思うことが
ある。たとえば、戦闘中に、殺すべき場面で敵を逃がしただとか、
殺されるとわかっているのに戦っただとか。そういう
不自然さがない。つまり登場人物が自然に行動している。
それは、登場人物が *現実にしそうなことをしている*
という意味ではなく、現実離れした行動をとっていても、
その行動にきちんと理由がついているということ。
さっき言った例だと、戦闘中に逃がすという行為も、
なにか理由があればするかもしれない。敵に同情した
だとか。不自然に感じるのは *理由もなく* そういう
行動をとった場合。その理由の説明が自然に理解できる、
ということ。

たとえば、物語のキャラクターであるリコは
スクラップにされそうになったロボットなのだけど、
リコは最初記憶を失っていて、スクラップにされそうだから
逃げてきたということになってる。これは定義だから
疑うようなことじゃない。そのあと、リコと出会った
主人公の希海は、リコに帰らないほうがいいと言う。
もしリコがただの家出娘なら、そう言う言葉を言うのは
不自然だ。でもその言葉が「帰ればスクラップにされて殺される」
というリコの事情を理由として自然な言葉になっている。
そのあと、1時間ほどして東という人がリコを取り返しにくる
のだ。それも希海の自宅に。いきなりの来訪で、読者が
いちばんに思うのは「どうして場所がわかったんだ？」
ということだ。この理由が説明されないと、
読者は違和感を感じて話が不自然になる。そこで
リコはロボットだから会社がきちんと管理するために
GPSで追っていたと説明される。これも自然に納得できることだ。

まぁそのあともいろいろと続くのだけど、
基本的に話の流れとして、「読者か不自然に思うことには
すべて理由を付け足す」という原則が守られている。
そのおかげで違和感なくすらすらと読める。

砂漠の巨人では、けっこう多い場面で「どうして
そういう行動をとるんだ？？？」と思うことがあった。
たとえば、リツコはマッドベースで出会ったサゴマの医師に、
初対面であり、しかもその医師は仕事中で忙しいにも
関わらず、単に話したいからという理由で突然いろいろ
な話をされる。その行動があまりにも不自然に感じた。
内容は主に世界観を説明することであり、もちろん
作者が世界観をアピールしたいのはわかるけど、その
描写の仕方がへただなと思った。「どうしてそういう
話をするんだろう？」という疑問に対してなんの理由も
加えられなかったからだ。

一方で、ふたりのハードプロブレムでは、
世界観の展開の仕方がうまい。たとえば、途中で
東がヒューマノイドのあり方を説明しだすのだ。
これは内容だけ見ればサゴマの医師が話していたのと
同じようにも思える、世界観に関する注釈のような
内容だ。だけどその話をする理由が「希海の誤解を
解きたいから」とはっきりしていて、話の流れに
違和感を感じなかった。もし同じ内容を、
出会い頭に突然話し始めていたら不自然に感じるだろう。
だけど、あくまで「希海の疑念を晴らしたいから、
話したいわけじゃないが話している」という体裁を
とっていることで、違和感なくすらすらと読むことができる。

話の流れに違和感や不自然に感じることは、
読む際に喉に突っかかる魚の骨みたいなもので、
いがらっぽい印象を与え、読みにくくすると思う。

コンパイラに求められるもっとも重要な事項は
なんだと思う？　それはコンパイル速度でもより
高度な最適化でもなく、正しさだ。つまり、
コードが、規格通りに正しく動作するということ
を保証するのが、コンパイラに求められるもっとも
重要な事項であり、たとえば、もし最適化をかけて
正しくないコードが生まれる可能性がすこしでもあるならば、
最適化はしないほうがいい。

小説に求められるいちばん大事な要素も、
正しさだと思う。つまり、読者が感じる疑念や違和感、
不自然さなんてものをできるだけ排除することが
小説が最初に目指すべき形だ。

そういうことを感じたわけである。

話の展開として、物語のキモになりそうな
設定を中盤まで明らかにされていないって感じがする。
いま、ふたりのハードプロブレムには
3章ある。1章では物語全体の世界観が
大雑把に説明される。2章にはあまり特徴はない。
3章には物語のキモとなりそうな設定が明らかにされる。
4,5章はまだ公開されていないけど、
たぶん3章で明らかにされた設定が活躍するのだろう。
楽しみである。
